# Generated by Django 4.2.28 on 2026-02-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('property', 'Property'), ('stock', 'Stock'), ('fund', 'Fund'), ('bond', 'Bond'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ticker_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('distribution_type', models.CharField(choices=[('regular', 'Regular'), ('special', 'Special'), ('return_of_capital', 'Return of Capital'), ('liquidating', 'Liquidating')], default='regular', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='api.asset')),
            ],
            options={
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('LLC', 'LLC'), ('trust', 'Trust'), ('partnership', 'Partnership'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EntityAssetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='api.asset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='api.entity')),
            ],
            options={
                'ordering': ['asset', 'entity'],
            },
        ),
        migrations.CreateModel(
            name='DistributionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('notes', models.TextField(blank=True, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.distribution')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_allocations', to='api.entity')),
            ],
            options={
                'ordering': ['distribution', 'entity'],
            },
        ),
    ]
