# Generated by Django 4.2.29 on 2026-03-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fmvsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='api.asset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='api.entity')),
            ],
            options={
                'ordering': ['entity', 'asset'],
                'unique_together': {('entity', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='CapitalCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_calls', to='api.commitment')),
            ],
            options={
                'ordering': ['call_date'],
            },
        ),
    ]
