# Generated by Django 4.2.29 on 2026-03-04 11:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_commitment_capitalcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='K1Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('asset_type_classification', models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('public_equity', 'Public Equity'), ('private_equity', 'Private Equity'), ('fixed_income', 'Fixed Income'), ('cash', 'Cash & Equivalents'), ('hedge_fund', 'Hedge Fund'), ('crypto', 'Cryptocurrency'), ('collectible', 'Collectible'), ('other', 'Other')], max_length=50, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('is_amended', models.BooleanField(default=False)),
                ('document', models.FileField(upload_to=api.models.k1_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('extraction_method', models.CharField(choices=[('text', 'Text'), ('ocr', 'OCR')], default='text', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k1_documents', to='api.asset')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='k1_documents', to='api.entity')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='K1PartnershipInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('irs_center', models.CharField(blank=True, default='', max_length=100)),
                ('is_ptp', models.BooleanField(default=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_info', to='api.k1document')),
            ],
            options={
                'verbose_name': 'K-1 Partnership Info',
                'verbose_name_plural': 'K-1 Partnership Info',
            },
        ),
        migrations.CreateModel(
            name='K1PartnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tin', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_general_partner', models.BooleanField(default=False)),
                ('is_domestic', models.BooleanField(default=True)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('is_retirement_plan', models.BooleanField(default=False)),
                ('profit_beginning_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('profit_ending_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('loss_beginning_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('loss_ending_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('capital_beginning_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('capital_ending_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('nonrecourse_beginning', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nonrecourse_ending', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qualified_nonrecourse_beginning', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('qualified_nonrecourse_ending', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recourse_beginning', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('recourse_ending', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_lower_tier_liabilities', models.BooleanField(default=False)),
                ('has_guarantee_obligations', models.BooleanField(default=False)),
                ('section_704c_beginning', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('section_704c_ending', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('built_in_gain', models.BooleanField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_info', to='api.k1document')),
            ],
            options={
                'verbose_name': 'K-1 Partner Info',
                'verbose_name_plural': 'K-1 Partner Info',
            },
        ),
        migrations.CreateModel(
            name='K1IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(max_length=10)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raw_text', models.CharField(blank=True, default='', max_length=500)),
                ('is_supplemental', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_items', to='api.k1document')),
            ],
            options={
                'ordering': ['line_number', 'code'],
            },
        ),
        migrations.CreateModel(
            name='K1CapitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('capital_contributed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('other_increase_decrease', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('withdrawals', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_basis_method', models.CharField(blank=True, default='', max_length=50)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_account', to='api.k1document')),
            ],
            options={
                'verbose_name': 'K-1 Capital Account',
                'verbose_name_plural': 'K-1 Capital Accounts',
            },
        ),
    ]
