# Generated by Django 4.2.29 on 2026-03-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_k1_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='source_k1_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to='api.k1document'),
        ),
    ]
