# Generated by Django 4.2.29 on 2026-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_source_k1_to_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('real_estate', 'Real Estate'), ('venture_capital', 'Venture Capital'), ('private_equity', 'Private Equity'), ('hedge_fund', 'Hedge Fund'), ('credit', 'Credit'), ('co_investment', 'Co-Investment'), ('infrastructure', 'Infrastructure'), ('natural_resources', 'Natural Resources'), ('public_equity', 'Public Equity'), ('fixed_income', 'Fixed Income'), ('cash', 'Cash & Equivalents'), ('crypto', 'Cryptocurrency'), ('collectible', 'Collectible'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='k1document',
            name='asset_type_classification',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('venture_capital', 'Venture Capital'), ('private_equity', 'Private Equity'), ('hedge_fund', 'Hedge Fund'), ('credit', 'Credit'), ('co_investment', 'Co-Investment'), ('infrastructure', 'Infrastructure'), ('natural_resources', 'Natural Resources'), ('public_equity', 'Public Equity'), ('fixed_income', 'Fixed Income'), ('cash', 'Cash & Equivalents'), ('crypto', 'Cryptocurrency'), ('collectible', 'Collectible'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
