# Generated by Django 4.2.29 on 2026-03-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_expand_asset_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('beginning_basis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('contributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest', models.DecimalField(decimal_places=2, default=0, help_text='K-1 Line 5', max_digits=15)),
                ('dividends', models.DecimalField(decimal_places=2, default=0, help_text='K-1 Line 6', max_digits=15)),
                ('capital_gains', models.DecimalField(decimal_places=2, default=0, help_text='K-1 Lines 8/9/10', max_digits=15)),
                ('remaining_k1_income', models.DecimalField(decimal_places=2, default=0, help_text='Remaining K-1 income/deductions', max_digits=15)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, help_text='Sum of income components', max_digits=15)),
                ('distributions', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_adjustments', models.DecimalField(decimal_places=2, default=0, help_text='K-1 Line 18-c', max_digits=15)),
                ('ending_tax_basis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ending_gl_balance', models.DecimalField(decimal_places=2, default=0, help_text='Ending GL Balance Per Books', max_digits=15)),
                ('book_to_tax_adj', models.DecimalField(decimal_places=2, default=0, help_text='GL Ending - Tax Basis', max_digits=15)),
                ('ending_k1_capital', models.DecimalField(decimal_places=2, default=0, help_text='Ending K-1 Capital Account', max_digits=15)),
                ('k1_capital_vs_tax_diff', models.DecimalField(decimal_places=2, default=0, help_text='K-1 Capital vs Tax Basis Difference', max_digits=15)),
                ('excess_distribution', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('negative_basis', models.BooleanField(default=False)),
                ('basis_change', models.DecimalField(decimal_places=2, default=0, help_text='Δ Ending Basis vs Prior Year', max_digits=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.asset')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.entity')),
                ('source_k1_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_records', to='api.k1document')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['entity', 'asset', 'year'],
                'unique_together': {('year', 'entity', 'asset')},
            },
        ),
    ]
